### ISSUE TITLE
Creating a FSDirectory throws exception

### ISSUE THREAD

**Issue by bahaabeih** [FlexSearch/FlexLucene#10]
I am using a `FSDirectory` in FlexLucene v6.0.0 as follows:
```
java.io.File f = new java.io.File(IndexDir.FullName);
java.nio.file.Path p = f.toPath();                                     //This line 
//java.nio.file.Path p = Paths.get(IndexDir.FullName);  //and this alternative line too
FSDirectory fsDir = FSDirectory.Open(p);
```
The lines marked both throw the following exceptions respectively. Although the methods `toPath` and `get` show up in intellisense.

> 'java.lang.NoSuchMethodException' in IKVM.OpenJDK.Core.dll  //For first line
>  'java.lang.NoSuchMethodError' in IKVM.Runtime.dll                    //and this for the alternate line

Any idea why this happens?

**Comment by vladnega** [comment]
Could you please try it using FlexLucene 6.0.1.0 ?

**Comment by bahaabeih** [comment]
Did so and they no longer get thrown. Is it a known problem?

**Comment by vladnega** [comment]
No, it wasn't a known problem. Maybe it got fixed by [this commit](https://github.com/FlexSearch/FlexLucene/commit/bfac593c75652266ed6fbd117a605138b774e206).
